### ISSUE TITLE
No Module Named CopyJob

### ISSUE THREAD

**Issue by ditServices** [OTTOMATIC-IO/ocopy#18]
When running the sample file on the readme I get the following error:

Traceback (most recent call last):
  File "sample.py", line 5, in <module>
    from ocopy.copy import CopyJob
ImportError: cannot import name 'CopyJob'

followed instructions as per readme

**Comment by cbenhagen** [comment]
Hi,

Unfortunately I am unable to reproduce the issue. Did you install ocopy with `pip3 install -U ocopy`? Where did you create your `sample.py`? Which Python version are you using and how did you install it? And on which operating system?

**Comment by ditServices** [comment]
Fixed by updating to Python 3.8 from 3.6.

**Comment by cbenhagen** [comment]
Ok good to know. What OS are you running it on? The test suite runs on Python 3.7, 3.8, nightly and on Linux, macOS and Windows: https://travis-ci.org/OTTOMATIC-IO/ocopy

Do you think there is a need to support older Python versions?

**Comment by ditServices** [comment]
I had the most issues on Linux (Ubuntu) Once I updated Python and fiddled around with pip, it worked ok. I had a fresh install of Python 3.8 on my Windows build and it all worked first time. Couldn't say about supporting older versions, I just had 3.6 on my development system as I never had a need to update before that.
